markdown: rdiscount
pygments: true
permalink: /posts/:title.html
rdiscount:
  extensions: [smart]

title: Liyichao's Weblog
author:
  name: liyichao
  email: liyichao.good@gmail.com
  github: liyichao

production_url: http://liyichao.github.io/
